### PR TITLE
Link to hosted cuttlefish rather than project site

### PR DESCRIPTION
**Pull request by mlandauer**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Let me know when edits complete :)

**Comment by mlandauer** [comment]
@jpmckinney this PR is complete. I'll do another one to add an example if that works for you?

**Comment by jpmckinney** [comment]
Sure! Ok to merge #117?

**Comment by mlandauer** [comment]
@jpmckinney please merge away! ;-)

**Pull request merged**
