### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by MyfanwyNixon**
OK, thanks for your understanding :s 
This is now all in html and it looks better to me. maybe take a look at it yourself before merging :)

### CODE REVIEW

**Comment by maugsbur** [comment]
Merged it, but there's a few problems with the indentation of the last part (chinese), so I rolled it back again... My personal opinion is that markup is better since it's a lot easier and cleaner, and therefore people don't make these kinds of errors.

If you edit through github you can also preview the changes, or once you make the pull request, you can algo preview it by going to "files changed" -> "rendered"

**Comment by MyfanwyNixon** [comment]
I can see what the issue is - it just needs a &lt;/ul> at the end of line 87. Can you add that, or is there an easy way for me to edit this without starting again? Thanks.

**Comment by maugsbur** [comment]
There, changed :) I was a bit busy last week, sorry about that.

**Comment by MyfanwyNixon** [comment]
Thank you so much :D

**Pull request merged**
