### PR TITLE
Add post about Cuttlefish hosted service for the Poplus community

### PR DESCRIPTION
**Pull request by mlandauer**

### CODE REVIEW

**Comment by davewhiteland** [comment]
Great post @mlandauer (and lovely re: the hosting). Not sure if I should have spotted this before, but I _think_ you should have a space in "setup" in your image tagline though (i.e., "easy to **set up**").

**Comment by mlandauer** [comment]
@davewhiteland well spotted. How is it I've never noticed this either? ;-) Hmm...

**Comment by mlandauer** [comment]
Fixed on cuttlefish.oaf.org.au and fixed in the image on the post :-)

**Comment by jpmckinney** [comment]
Anything preventing merge?

**Comment by lfalvarez** [comment]
:+1: I'm going to merge it

**Comment by lfalvarez** [comment]
There we go [/posts/email-is-your-secret-weapon/](http://poplus.org/posts/email-is-your-secret-weapon/)

**Pull request merged**
