### PR TITLE
Copy edits

### PR DESCRIPTION
**Pull request by MyfanwyNixon**
Hopefully made this page a bit easier to understand for people who weren't at the conference.

### CODE REVIEW

**Comment by MyfanwyNixon** [comment]
Oops, sorry Marcel - it looks like I did something stupid with the links:
http://poplus.org/popluscon/ Is my mark-up wrong?

Myf

On Fri, May 30, 2014 at 2:41 PM, Marcel Augsburger <notifications@github.com

**Comment by maugsbur** [comment]
Yes, several things look awful... I'm doing rollback right now

2014-05-30 9:47 GMT-04:00 MyfanwyNixon notifications@github.com:

**Comment by maugsbur** [comment]
Looking at the code, it seems the problem is you use both html and markup.
All the tags between <> are html, and there's no reason to use them in this
page.

2014-05-30 10:00 GMT-04:00 Marcel Augsburger maugsburger@gmail.com:

**Comment by MyfanwyNixon** [comment]
damn it, thanks Marcel! I'll have an edit in just a mo.

Myf

On Fri, May 30, 2014 at 3:50 PM, Marcel Augsburger <notifications@github.com

**Comment by maugsbur** [comment]
No problem, just part of the learning process ;)

2014-05-30 10:51 GMT-04:00 MyfanwyNixon notifications@github.com:

**Pull request merged**
